version: "3.9"

services:
  apps:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000

  npm:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    entrypoint: ["npm"]
